<?php

namespace modava\auth\models\table;

use cheatsheet\Time;
use modava\auth\models\query\UserOtpQuery;
use Yii;
use yii\db\ActiveRecord;

class UserOtpTable extends \yii\db\ActiveRecord
{
    const STATUS_NOT_ACTIVE = 0; //Mã otp chưa được sử dụng
    const STATUS_ACTIVE = 1; //Mã đã được sử dụng

    public static function tableName()
    {
        return 'user_otp';
    }

    public static function find()
    {
        return new UserOtpQuery(get_called_class());
    }

    public function afterDelete()
    {
        $cache = Yii::$app->cache;
        $keys = [];
        foreach ($keys as $key) {
            $cache->delete($key);
        }
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }

    public function afterSave($insert, $changedAttributes)
    {
        $cache = Yii::$app->cache;
        $keys = [];
        foreach ($keys as $key) {
            $cache->delete($key);
        }
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }
}
