<?php

namespace modava\auth\controllers;

use modava\auth\models\form\LoginForm;
use modava\auth\components\MyAuthController;
use modava\auth\models\User;
use Yii;


class AuthController extends MyAuthController
{
    public function behaviors()
    {
        return parent::behaviors(); // TODO: Change the autogenerated stub
    }

    public function actionIndex()
    {
        return $this->redirect(['login']);
    }

    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->redirect(['/site/index']);
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->redirect(['/site/index']);
        } else {
            $model->password = '';
        }

        return $this->render('login', [
            'model' => $model,
        ]);
    }

    public function actionResetPassword()
    {
        return $this->render('resetPassword', [

        ]);
    }

    public function actionRequestPasswordReset()
    {
        return $this->render('requestPasswordReset', [

        ]);
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();
        return $this->goHome();
    }
}
