<?php

namespace modava\auth\controllers;

use backend\models\auth\AuthForm;
use backend\models\auth\RequestPasswordResetForm;
use backend\models\LoginForm;
use modava\auth\components\MyAuthController;
use Yii;


class AuthController extends MyAuthController
{
    public function behaviors()
    {
        return parent::behaviors(); // TODO: Change the autogenerated stub
    }

    public function actionIndex()
    {
        return $this->redirect(['login']);
    }

    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }
        $model = new LoginForm();
        $modelAuth = new AuthForm();
        $modelResetPass = new RequestPasswordResetForm();
        return $this->render('login', [
            'model' => $model,
            'modelAuth' => $modelAuth,
            'modelResetPass' => $modelResetPass,
        ]);
    }

    public function actionResetPassword()
    {
        return $this->render('resetPassword', [

        ]);
    }

    public function actionRequestPasswordReset()
    {
        return $this->render('requestPasswordReset', [

        ]);
    }
}
