<?php


namespace modava\auth\components;


use backend\components\MyController;

class MyAuthController extends MyController
{
    public function behaviors()
    {
        return parent::behaviors(); // TODO: Change the autogenerated stub
    }
}