<?php


namespace modava\auth\components;


use backend\components\MyController;
use yii\web\Controller;

class MyAuthController extends Controller
{
    public function behaviors()
    {
        return parent::behaviors(); // TODO: Change the autogenerated stub
    }
}