<?php

namespace modava\auth\models;

use modava\auth\AuthModule;
use modava\auth\models\form\UserMetadataForm;
use yii\behaviors\AttributeBehavior;
use yii\db\ActiveRecord;

/**
 * UserMetadata model
 *
 * @property integer $user_id
 * @property array $metadata
 */
class UserMetadata extends ActiveRecord
{
    public $toastr_key = 'user-metadata';

    public $User;
    public $Pass;
    public $Display;
    public $Realm;
    public $WSServer;

    public function afterFind()
    {
        parent::afterFind(); // TODO: Change the autogenerated stub
        $this->setAttributes($this->metadata);
    }

    public function beforeSave($insert)
    {
        $this->metadata = [
            'Pass' => $this->Pass,
            'Display' => $this->Display,
            'User' => $this->User,
            'Realm' => $this->Realm,
            'WSServer' => $this->WSServer,
        ];
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function rules()
    {
        return [
            [['user_id'], 'required'],
            [['user_id'], 'integer'],
            [['user_id'], 'exist', 'targetClass' => User::class, 'targetAttribute' => 'id'],
            [['metadata', 'Pass', 'Display', 'User', 'Realm', 'WSServer'], 'safe'],
        ];
    }

    public function attributeLabels()
    {
        return [
            'Pass' => AuthModule::t('auth', 'Voip24h Pass'),
            'Display' => AuthModule::t('auth', 'Voip24h Display'),
            'User' => AuthModule::t('auth', 'Voip24h User'),
            'Realm' => AuthModule::t('auth', 'Voip24h Realm'),
            'WSServer' => AuthModule::t('auth', 'Voip24h WSServer'),
        ];
    }

    public function getUserHasOne()
    {
        return $this->hasOne(User::class, ['id' => 'user_id']);
    }
}